[package]
name = "rqcommon"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
log = "0.4.29"
chrono = { version = "0.4.43", features = ["serde"] }
chrono-tz = "0.10.4"
lettre = "0.11.19"